name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-integration:
    needs: test-security
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: Install dependancies
      run: npm install
    - name: Run integration tests
      run: npm run test-integration

  test-security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: Install dependancies
      run: npm install
    - name: Run security tests
      run: npm run test-security

  deploy:
    runs-on: ubuntu-latest
    needs: test-integration
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
          wait-for-success: true